name: Ubuntu
on:
  
  # push: # push触发
  #   branches: [ main ]
  watch:
    types: [started]
  # workflow_dispatch: # 手动触发
  # schedule: # 计划任务触发
  #   - cron: '*/30 22-23,0-15 * * *' # cron表达式，Actions时区是UTC时间，所以要往前推8个小时(6-23)
    
jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.2
      - name: Print Public IP
        run: |
          echo 'ipv4: ${{ steps.ip.outputs.ipv4 }}'
          echo 'ipv6: ${{ steps.ip.outputs.ipv6 }}'
      # - run: ./generate-certificates.sh
      #   env:
      #     FRPS_DOMAIN: ${{ secrets.FRPS_DOMAIN }}
      # - run: ./install-frp.sh
      # - name: run frpc
      #   env:
      #     RUNNER_PASSWORD: ${{ secrets.RUNNER_PASSWORD }}
      #     FRPS_DOMAIN: ${{ secrets.FRPS_DOMAIN }}
      #     FRPC_TLS_KEY: ${{ secrets.FRPC_TLS_KEY }}
      #     FRPC_TLS_CERTIFICATE: ${{ secrets.FRPC_TLS_CERTIFICATE }}
      #     FRPC_TLS_CA_CERTIFICATE: ${{ secrets.FRPC_TLS_CA_CERTIFICATE }}
      #     SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      #   run: ./run-frpc.sh
